[package]
name = "one_brc"
version = "0.1.0"
edition = "2021"
default-run = "one_brc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = { version = "0.2.1"}
